# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76fbecadab2e58a8d53f5b46b9ac9ead6803a7f1a806272fed337a8bf1966c86456eb3a29b5a655a04582b771a9ea1f2080949f0a098eb4771a2207c09a0cb7e

test:
  secret_key_base: 2e37901976f6b899a4fab9165a36d8050f6ecf5907ceb143f9b907d4ab97ceed43e46a8ba0a8ee5591507807c9cb57391a1805af29e4ea90a5c4a3da592acbb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
